"""Make account_credits non-nullable and set default for existing rows

Revision ID: 33c6781a7cf4
Revises: a75d8c58a387
Create Date: 2025-12-03 06:26:33.057253

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33c6781a7cf4"
down_revision = "a75d8c58a387"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        # Set default for existing rows before making non-nullable
        op.execute("UPDATE user SET account_credits = 0 WHERE account_credits IS NULL;")
        batch_op.alter_column(
            "account_credits",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_default=0,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "account_credits",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_default=0,
        )
    # ### end Alembic commands ###
