"""Add locale to user

Revision ID: 4617147cf581
Revises: 9cfe60efdaed
Create Date: 2025-12-03 11:22:02.094224

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4617147cf581"
down_revision = "9cfe60efdaed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locale", sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("locale")

    # ### end Alembic commands ###
