"""Add user profile and drafts

Revision ID: 9cfe60efdaed
Revises: 99230b197a60
Create Date: 2025-12-03 11:03:51.275289

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cfe60efdaed"
down_revision = "99230b197a60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "draft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("hive_account_username", sa.String(length=16), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tags", sa.String(length=256), nullable=True),
        sa.Column("permlink", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("tx_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("last_name", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("avatar_url", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("bio")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    op.drop_table("draft")
    # ### end Alembic commands ###
