"""Add default tags to groups

Revision ID: a6f788ece003
Revises: d5490e6c80c5
Create Date: 2025-12-09 11:15:37.965740

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6f788ece003"
down_revision = "d5490e6c80c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_tags", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group", schema=None) as batch_op:
        batch_op.drop_column("default_tags")

    # ### end Alembic commands ###
