"""Add account credits and PayPal orders

Revision ID: a75d8c58a387
Revises: be21eeaed23c
Create Date: 2025-12-03 05:17:29.790829

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a75d8c58a387"
down_revision = "be21eeaed23c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pay_pal_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("paypal_order_id", sa.String(length=64), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("credits_purchased", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paypal_order_id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_credits", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("account_credits")

    op.drop_table("pay_pal_order")
    # ### end Alembic commands ###
