"""add beneficiaries to draft

Revision ID: b7286b72eb38
Revises: 4617147cf581
Create Date: 2025-12-05 02:52:28.209702

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7286b72eb38"
down_revision = "4617147cf581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft", schema=None) as batch_op:
        batch_op.add_column(sa.Column("beneficiaries", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("draft", schema=None) as batch_op:
        batch_op.drop_column("beneficiaries")

    # ### end Alembic commands ###
