"""Initial migration

Revision ID: be21eeaed23c
Revises:
Create Date: 2025-12-03 05:07:23.040112

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be21eeaed23c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hive_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=16), nullable=True),
        sa.Column("password_enc", sa.Text(), nullable=True),
        sa.Column("keys_enc", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("tx_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hive_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hive_account_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hive_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hive_account_username"))

    op.drop_table("hive_account")
    # ### end Alembic commands ###
