"""add created_at to user

Revision ID: fe9c613cafe5
Revises: e76bc1928ad0
Create Date: 2025-12-20 04:18:31.432873

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe9c613cafe5"
down_revision = "e76bc1928ad0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
